"""initial schema with users, anubhavs, tags, reminders

Revision ID: d76368627fb4
Revises: 
Create Date: 2026-06-20 21:33:53.377711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # ← ADDED: needed for VECTOR column type


# revision identifiers, used by Alembic.
revision: str = 'd76368627fb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── Enable pgvector extension FIRST (required before VECTOR column) ──
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)

    op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('clerk_user_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table('anubhavs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('what_happened', sa.Text(), nullable=False),
        sa.Column('lesson', sa.Text(), nullable=True),
        sa.Column('advice', sa.Text(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('category', sa.Enum('CAREER', 'RELATIONSHIPS', 'HEALTH', 'MONEY', 'MINDSET', 'LIFE', name='category_enum'), nullable=False),
        sa.Column('source', sa.Enum('MYSELF', 'FRIEND', 'BOOK', 'PODCAST', 'OBSERVATION', name='source_enum'), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anubhavs_user_id'), 'anubhavs', ['user_id'], unique=False)

    op.create_table('anubhav_tags',
        sa.Column('anubhav_id', sa.UUID(), nullable=False),
        sa.Column('tag_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['anubhav_id'], ['anubhavs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('anubhav_id', 'tag_id')
    )

    op.create_table('reminders',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('anubhav_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('trigger_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'SENT', 'CANCELLED', name='reminder_status_enum'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['anubhav_id'], ['anubhavs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_anubhav_id'), 'reminders', ['anubhav_id'], unique=False)
    op.create_index(op.f('ix_reminders_trigger_at'), 'reminders', ['trigger_at'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_trigger_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_anubhav_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('anubhav_tags')
    op.drop_index(op.f('ix_anubhavs_user_id'), table_name='anubhavs')
    op.drop_table('anubhavs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')

    # ── Drop pgvector enums + extension LAST ──
    sa.Enum(name='category_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='source_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='reminder_status_enum').drop(op.get_bind(), checkfirst=True)
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###